---
title:                                  Curriculum Vitae
tagline:                                Short version
date:                                   2022-01-01 00:00:00
description: >
                                        Things you should know about this site,
                                        the people and the software and/or
                                        services provided.

tags:                                   [ Overview ]
categories:                             [ Software, Platforms, Contributers ]

scrollbar:                              false

permalink:                              /pages/public/resume/
regenerate:                             false

resources:                              [
                                          animate, lightGallery, justifiedGallery, video_js,
                                          vimeo_player, vimeo_froogaloop, clipboard, lightbox, rouge
                                        ]
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/modules/attics/sigmund-1920x1280.jpg
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:badges-enabled:                        true

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

ifeval::[{badges-enabled} == true]
{badge-j1--license} {badge-j1--version-latest} {badge-j1-gh--last-commit} {badge-j1--downloads}
endif::[]

// Include sub-documents (if any)
// -----------------------------------------------------------------------------

== Personal Details

Name:: Saul Diaz Infante Velasco
Address:: Mariano Jiménez, 833, Col. Nueva Castilla, Hermosillo, Sonora, Mexico.
CP:: 83126
phone numbers: +52 473 75 60 109,
e-mail:: saul.diazinfante@unison.mx

== Education

.Degrees
[cols="1,2,1"]
|===
|Grade |Institution |Grade

|Bacherols degree on Electronic and computation
|Centro de Enseñanza Tecnico Industrial CeTi, Guadalajara Jalisco, Mexico
|1997-2002
#
|Bacherols degree in Mathematics
|Centro Universtiario de Ciencias Exactas e Ingenirías,
Universidad de Guadalara, Guadalaraja, Jalisco, Mexico.
|2001-2005

|Master in Eductation for Mathematics
|Universidad Autonoma de Guadalara, Guadalajra, Jalisco, Mexico
|2006-2008

|Master in Science on Applied Mathematics
|Centro de Investigacion en Matemáticas, A.C. CIMAT, Guanajuato, Guanajuato, Mexico
|2009-2011

|Phd in Applied Mathematics
|Centro de Investigacion en Matemáticas, A.C. CIMAT, Guanajuato, Guanajuato, Mexico
|2011-2015

|===

// -----------------------------------------------------------------------------
== Publications

=== Accepted peer-reviewed articles

++++
{% bibliography --file references.bib --query @Article[] %}
++++

=== Submited peer-reviewed articles

=== Book chapters

++++
{% bibliography --file references.bib --query @InBook %}
++++

=== Forthcoming Publications
lorem:sentences[5]

=== Thesis
lorem:sentences[5]

== Research
lorem:sentences[5]

== Honors and awards
lorem:sentences[5]

== Funding
lorem:sentences[5]

== Teaching

++++
<table>
    <tr>
        <td></td>
        <td>Key</td>
        <td>subject-matter</td>
        <td>DEPARTAMENTO</td>
        <td>Hours/week</td>
        <td>LEVEL</td>
    </tr>
    <tr>
        <td>CINVESTAV-Monterrey</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>2016-1</td>
        <td>---</td>
        <td>Systems Biology</td>
        <td></td>
        <td>4</td>
        <td>Master</td>
    </tr>
    <tr>
        <td>UNIVERSIDAD DE SONORA</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>2016-2</td>
        <td>01626</td>
        <td>SELECTED PROBABILITY TOPICS</td>
        <td>Math</td>
        <td>8</td>
        <td>Master's degree</td>
    </tr>
    <tr>
        <td>2017-1</td>
        <td>01627</td>
        <td>SELECT TOPICS OF STOCHASTIC PROCESSES</td>
        <td>Math</td>
        <td>8</td>
        <td>Master's degree</td>
    </tr>
    <tr>
        <td>2017-2</td>
        <td>01635</td>
        <td>SELECT TOPICS IN NUMERICAL ANALYSIS</td>
        <td>Math</td>
        <td>8</td>
        <td>Master's degree</td>
    </tr>
    <tr>
        <td>2018-1</td>
        <td>01633</td>
        <td>CONTROL THEORY</td>
        <td>Math</td>
        <td>4</td>
        <td>Master's degree</td>
    </tr>
    <tr>
        <td>2018-2</td>
        <td>01636</td>
        <td>SELECT TOPICS IN APPLIED MATHEMATICS</td>
        <td>Math</td>
        <td>8</td>
        <td>Master's degree</td>
    </tr>
    <tr>
        <td>2019-1</td>
        <td>01634</td>
        <td>NUMERICAL ANALYSIS</td>
        <td>Math</td>
        <td>4</td>
        <td>Master's degree</td>
    </tr>
    <tr>
        <td>2019-1</td>
        <td>01638</td>
        <td>THESIS SEMINAR</td>
        <td>Math</td>
        <td>4</td>
        <td>Master's degree</td>
    </tr>
    <tr>
        <td>2019-2</td>
        <td>01627</td>
        <td>SELECT TOPICS OF STOCHASTIC PROCESSES</td>
        <td>Math</td>
        <td>8</td>
        <td>Master's degree</td>
    </tr>
    <tr>
        <td>2020-1</td>
        <td>00164</td>
        <td>RESEARCH SEMINAR IV</td>
        <td>Math</td>
        <td>4</td>
        <td>doctor's degree</td>
    </tr>
    <tr>
        <td>2020-2</td>
        <td>01631</td>
        <td>OPTIMIZATION</td>
        <td>Math</td>
        <td>8</td>
        <td>doctor's degree</td>
    </tr>
    <tr>
        <td>2021-1</td>
        <td>01633</td>
        <td>CONTROL THEORY</td>
        <td>Math</td>
        <td>4</td>
        <td>doctor's degree</td>
    </tr>
    <tr>
        <td>2021-2</td>
        <td>01635</td>
        <td>SELECT TOPICS IN NUMERICAL ANALYSIS</td>
        <td>Math</td>
        <td>8</td>
        <td>doctor's degree</td>
    </tr>
    <tr>
        <td>2022-1</td>
        <td>00270</td>
        <td>MATHEMATICAL PROGRAMMING</td>
        <td>Math</td>
        <td>6</td>
        <td>Bachelor's degree</td>
    </tr>
</table>
++++

== Administrative Experience
lorem:sentences[5]

== Professional  Experience
lorem:sentences[5]

== Other skills and qualifications
lorem:sentences[5]

== Professional affiliations and memberships
AMS, mex-SIAM, SMM

== online Presentations
++++
<!-- insert Google Ad (Displayanzeige): horizontal-2, adSlot="5128488466" -->
<div class="5128488466 mb-5">
  <ins class="adsbygoogle"
    style="display: block;"
    data-ad-client="ca-pub-3885670015316130"
    data-ad-slot="5128488466"
    data-ad-format="auto"
    data-adtest="on"
    data-full-width-responsive="true">
  </ins>
</div>
++++

++++
<script>
  $(document).ready(
    function() {
        var logger              = log4javascript.getLogger('j1.google.ads');
        var autoHideOnUnfilled  = true;
        var dependencies_met_page_ready = setInterval (
            function (options) {
                if ( j1.getState() === 'finished' ) {
                    // monitor for state changes on the ad
                    // ---------------------------------------------------------------------
                    $('.adsbygoogle').attrchange({
                      trackValues: true,
                        callback: function (event) {
                            if (event.newValue === 'unfilled') {
                                var elm = event.target.dataset;
                                if (elm.adClient) {
                                    logger.warn('\n' + 'initialized ad detected as: ' + event.newValue);
                                    if (autoHideOnUnfilled) {
                                        logger.info('\n' + ' hide ad for slot: ' + elm.adSlot);
                                        $('.' + elm.adSlot ).hide();
                                    }
                                }
                            }
                        }
                    });
                    logger.info('\n' + 'initialize Google Ad on slot: ' + '5128488466');
                    (adsbygoogle = window.adsbygoogle || []).push({});
                    clearInterval(dependencies_met_page_ready);
                }
            }
        );
    }
  );
</script>
++++

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="dropcap"]
Mini Course on modelling and numerics with SDEs at the School of
Optimal Control Applies to Biolgical Processes.

== Online Video content

=== YouTube

.Short Course
gallery::jg_video_online_youtube[role="mb-5"]


gallery::jg_video_online_youtube[role="mb-5"]

== Attendance at conferences and seminars

== 2011

== 2012

== 2013

== 2014

== 2015

== 2016

== 2017

== 2018

=== 2019

++++
{% bibliography --file references.bib --query @Unpublished[year=2019] %}
++++

=== 2020

++++
{% bibliography --file references.bib --query @Unpublished[year=2020] %}
++++

=== 2021

++++
{% bibliography --file references.bib --query @Unpublished[year=2021] %}
++++

=== 2022

++++
{% bibliography --file references.bib --query @Unpublished[year=2022] %}
++++

++++
<script>
    $(document).ready(function(){
        var str =$(this).attr('id');

        $(".btnId").click(function(){
            var str = $(this).attr('id');
            var ret = str.split("_");
            var id = ret[1];
            $('#' + id).toggle();
        });
    });
</script>
++++

== References

++++
include::./pages/public/resume/references.html[]
++++

== Appendices
