---
title:
    Threshold behaviour of a stochastic vector
  plant model for Tomato Yellow Curl Leaves disease
tagline:
  a study based on mathematical analysis and simulation

date:                                   2022-01-01 00:00:00
description: >
  TODO: Rewrite

categories:                             [ Knowledge ]
tags:                                   [ Asciidoc, Skeleton, Document ]

robots:
  index:                                false
  follow:                               false

permalink:                              /pages/public/preprints/sto_mle/main_sto_tycl/
regenerate:                             false

resources:                              [animate, clipboard, carousel,
                                          justifiedGallery, lightbox, lightGallery,
                                          rouge]
resource_options:
  - attic:
      slides:
        - url:                          /assets/images/modules/attics/annie-spratt-1920x1280.jpg
          alt:                          Photo by Annie on Unsplash
          alignY:                       0.3
          badge:
            type:                       unsplash
            author:                     Sigmund
            href:                       https://unsplash.com/@sigmund
---
// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:
:badges-enabled: true

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="all" %}

:images-dir: {imagesdir}/pages/preprints/sto_tycl/figrues

// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
:stem: latexmath
:eqnums: AMS
:xrefstyle: short
:section-refsig: Section
:toc:
:prose: text-indent-inner: 18
++++
<script>
    MathJax = {
        loader: {load: ['[tex]/textmacros']},
        tex: {
            inlineMath: [['$', '$'], ['\\(', '\\)']],
            tags: 'ams',
            packages: {'[+]': ['textmacros']},
            macros: {
                oe: '\u0153',
                OE: '\u0152',
                ae: '\u00E6',
                AE: '\u00C6',
                aa: '\u00E5',
                AA: '\u00C5',
                o: '\u00F8',
                O: '\u00D8',
                l: '\u0142',
                L: '\u0141',
                ss: '\u00DF',
                SS: '\u1E9E',
                dag: '\u2020',
                ddag: '\u2021',
                P: '\u00B6',
                copyright: '\u00A9',
                pounds: '\u00A3'
            }
        },
        chtml: {
            mtextInheritFont: true
        },
        sag: {
            mtextInheritFont: true
        },
        svg: {fontCache: 'global'}
    };
</script>
<script
        async id="MathJax-script"
        src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js">
</script>
<style>
    .theorem {
        display: block;
        font-style: italic;
    }
    p{
        text-indent: 30px;
    }
    .theorem:before {
        content: "Theorem. ";
        font-weight: bold;
        font-style: normal;
    }
    .theorem[text]:before {
        content: "Theorem (" attr(text) ") ";
    }
    .definition {
        display: block;
        font-style: italic;
    }
    .definition:before {
        content: "Definition. ";
        font-weight: bold;
        font-style: normal;
    }
    .definition[text]:before {
        content: "Definition (" attr(text) ") ";
    }
    .proof {
        display: block;
        font-style: italic;
    }
    .proof:before {
        content: "Proof. ";
        font-weight: bold;
        font-style: normal;
    }
    .proof[text]:before {
        content: "Proof (" attr(text) ") ";
    }
    span.right{
        float:right
    }
</style>
++++


== Abstract
Diseases transmitted by vectors in crops represent a severe risk to
the farmer, causing low production and lower quality, which results
in a drastic reduction in crop yield. Here we study a stochastic
plant-vector-host epidemic model with direct transmission.
Perturbing with Brownian motion plant replanting and vector
fumigation rates, we formulate an Ito stochastic differential
equations that capture the uncertainty of the controls.
We derive conditions to assure extinction and persistence
of disease using two different stochastic versions of the so-called
basic reproductive number.
Finally, we verify and illustrate our theory by numerical experiments.
Our simulations suggest that uncertainty could drive dramatic stability changes.
Because in practice, to confirm an infected plant via laboratory
tests is not necessarily feasible, replanting and fumigation strategies
suffer considerable uncertainty.
Here, we quantify and study the impact and consequences of this uncertainty.
We conclude that environmental noise promotes dramatic stability
changes.

=== Keywords
    Tomato yellow curl virus disease, stochastic Model, threshold behaviour,
    vector-plant-host, persistence, extinction, Brownian motion

== Introduction

Whitefly (Bemisia tabaci) is the responsible vector for
critical insect-transmitted diseases in crops like
tomato, soybeans, and cotton
+++{% cite Yan2021 faiz2021 Swathi2021 Ali2021 %}+++.
Begomoviruses transmitted by this insect provoke reductions in the
production and quality of this and other products in India, Mexico,
USA, Colombia, and other producer countries
+++{% cite Li2021 Lee2021 %}+++.
For example, Tomato Yellow Curl Lives (TYCL) disease cause that tomato
plants to become futile and diminish their growth
+++{% cite Yan2021 Cohen2007 %}+++.

Despite control strategies like fumigation or replanting,
it is complicated to eradicate this vector. This insect has
sophisticated survival mechanism that permits shelter itself
in another perennial--and abundant on the borders of
the plantation--insecticide-resistant plants.
Thus, fumigation promotes partial migration instead of extinction.
In addition, plant symptoms like curl leaves and yellow
discolouration also are associated with iron or phosphate soil
deficiencies. Consequently, control methods like replanting
neighbours or physical barriers suffer from high
uncertainty--a farmer could replant a healthy plant instead of
a latent one and vice-versa.

There is well-established literature that treats deterministic
models for vector plant structures. Our primary reference is the work of
+++{% cite Holt1999 Cohen2007 Chan1994 %}+++ and other important reference.
Recently, control strategies have been studied as optimal control
problems by Lenhart et al. in
+++{% cite Bokil2019 %}+++
for a tomato diseaseand Luo et al. +++{% cite Luo2021 %}+++ for Huanglongbing.
However, the uncertainty quantification or stochastic counterparts
still are under development. In this direction, we mention the
recent works of Allen et al. +++{% cite Hebert2016 %}+++, Stella \& Ghosh
+++{% cite Stella2019 %}+++ Agarwal et al. +++{% cite Agarwal2019 %}+++,
and Chen-Charpentier +++{% cite Chen-Charpentier2021 %}+++
as significant contributions.

Here, we aim to quantify the uncertainty due to possible errors
in identifying infected plants and random fluctuations of vector
migration produced in fumigation. Our study attempts to capture
the impact of ambient noise and try to explain it by formal
analysis and simulation.

According to Britton et al. +++{% cite Britton2019 %}+++, stochastic effects
of an epidemic model are essential when the underlying
population size is relatively small (at most hundreds).
However, recently have been reported studies that attempt
the same methodology of deterministic models in
mathematical epidemiology—being positivity,
invariance, extinction, and persistence the primary
objects of study. In respect of this regard, we refer
the reader to
+++{% cite Gray2011 Cao2016a Acuna-Zegarra2018 %}+++.
However, the application to a specific disease
driven with data is still under development.
Roughly speaking, the methodology bases
the analysis on study versions of a SIR structure
and characterizes conditions to extinction-persistence
for a convenient definition of a stochastic
reproductive number, see +++{% cite Cao2016a  ZhaoJiang2015 Rifhat2021 Ji2014 %}+++.

Regarding plant-vector-host structures, we see relevant
the contributions of Allen et al. +++{% cite Gray2011 %}+++
and Agarwal et al. +++{% cite Agarwal2019 %}+++.
These works would apply the most common techniques to
formulate stochastic models for epidemics
based on Ito differential equations. Agarwal studied
pine wilt disease with a stochastic optimal control
problem, where the controls are related to prevention and
fumigation. Allen considers a stochastic plant-vector-host
structure deduced as the limit of a Continuous Markov chain
model. With this structure, Allen et al. study the effects
of vector aggregation and dispersal subject to noise.
On this occasion, we deploy a compartmental $SLI-SI$
plant vector structure with Brownian noise by formulating
an Itô stochastic differential equation (SDE).
Our main results characterize conditions to assure
extinction and persistence.
First, we identify requirements to ensure extinction
due only to noise intensity. Then, for sufficiently small noise, we
develop the threshold theory for two proposals of the
stochastic reproductive number. Finally, we verify and
illustrate our results by numerical simulation.

We aim to quantify the effects of uncertainty
of the mentioned controls over the extinction and persistence
of the disease.
We conclude that noise would play a crucial role
in the trade-off between extinction and persistence.
In other words, the combination of errors due by plant
identification and random fluctuations of vector migration
would lead to the death of healthy and infected plants and or
its prevalence.
Consequently, the local behaviour of vectors follows similar
codependency.

Using the package **DifferentialEquation.jl** from *Julia*
+++{% cite rackauckas2017differentialequations %}+++, we simulate
our stochastic model. This package provides the most
recent solvers for stiff Itô problems.
We apply the parallel implementation of **S-ROCK** method
+++{% cite Abdulle2008 %}+++---getting a stable, and high convergent
simulation of 10 000 paths after a reasonable computational
time.
Our simulations suggest that environmental noise induces large dispersion.
Thus, we deduce that uncertainty would lead to unexpected results.
Therefore, a significant implication is related to the good identification
of healthy crops---our recommendation is to balance replanting
with efficiency.

After this brief introduction, in link:#sec:model_formulation[Section 2]
we discuss the dynamic properties of the deterministic base. Then,
link:#sec:stochastic_extension[Section 3] extends this base by stochastic
perturbation to formulate our SDE model.  link:#sec:solution_existence[Section 4]
deploys the results about the existence and uniqueness of the global
positivity solution. After that, link:#sec:extinction[Section 5] characterizes
conditions on the noise intensity and other parameters to assure disease
extinction.  Then we complete the analysis with results to ensure disease
persistence in link:#sec:persistence[Section 6]. Finally in link:#sec:numerics[Section 7],
we verify and illustrate our theory with numerical experiments.

[#sec:model_formulation]
== Deterministic base dynamics
Here, we adapt the deterministic dynamics presented by
Holt et al. +++{% cite Holt1999 %}+++. Following the authors,
we split the plant population according to,
susceptible $ (S_p) $, latent $ (L_p) $, and infected
$ (I_p) $. And divide vector population into susceptible
$S_v$ and $I_v$ infected classes.
We consider the following assumptions: Susceptible plants become latent
plants when an infected vector feeds on them at constant rate, $\beta_p$.
Latent plants become infected plants at a rate of $b$. We replant latent and
infected plants that are detected at rate $r_1$ and $r_2$, respectively.
Removed plants are replanting as susceptible plants in the crop.
For vector dynamics, we consider that susceptible vectors become acquirer
disease, at rate $\beta_v$, when they eat an infected plant. We assume natural
vector die at rate $\gamma$, and by fumigation at rate $\gamma_f$. A proportion
of the susceptible and infected vectors migrates from alternatives host plants
to the crop.


With these hypotheses, the model has the following equations

[#eq:DeterministicSystem]
++++
	\begin{equation}
		\label{eq:DeterministicSystem}
		\begin{aligned}
			\dot{S_p} &=
				-\beta_p S_p
				\frac{I_v}{N_v} + r_1 L_p + r_2 I_p
			\\
			\dot{L_p} &=
				\beta_p S_p
				\frac{I_v}{N_v} - (b + r_1) L_p
			\\
			\dot{I_p} &=
				b L_p - r_2 I_p  \\
			\dot{S_v} &=
				-\beta_v S_v
				\frac{I_p}{N_p} - (\gamma + \gamma_f) S_v
				+(1-\theta) \mu
			\\
			\dot{I_v} &=
				\beta_v S_v \frac{I_p}{N_p}
				- (\gamma + \gamma_f) I_v
				+ \theta \mu
				 \\
				S_p(0) &=S_{p0}, \qquad
				L_p(0) = L_{p0}, \qquad
				I_p(0) = I_{p0},
				\\
				 S_v(0) &= S_{v0}, \qquad
				  I_v(0) = I_{v0},
				 \\
				 N_p(t) &= S_p(t) + L_p(t) + I_p(t),
				 \\
				 N_v(t) &= S_v(t) + I_v(t).
		\end{aligned}
	\end{equation}
++++

We conduct a calibration of the model
link:#eq:DeterministicSystem[(1)]
based on the parameters and data reported in
+++{% cite Holt1999 %}+++ and  via Multi Chain Montecarlo Method (MCMC).
Here we used the *R-Stan* implementation and followed the workflow from
+++{% cite Grinsztajn2021 %}+++.
We refer the reader to the supplementary material
+++{% cite Salcedo-varela2021 %}+++
for more details.

Figure link:#fig:fitnonresistance[ 1] and link:#fig:fitresistance[2]
show the confidence band, and the median for link:#eq:DeterministicSystem[model (1)]
to each tomato data set reported by +++{% cite Holt1999 %}+++.
autoref{tbl:parameter_value} displays the estimates of the parameters
for each tomato species.

[#tbl:deterministic_tbl]
[caption="Table 1. "]
.Parameters description of deterministic dynamics in ODE link:#eq:DeterministicSystem[(1)]
[cols="1,1,1"]
|===
| Par.| Description| Reference sources

| $\beta_p$
|infection rate of susceptible plants by infected vectors
|+++{% cite Butter1978%}+++, +++{% cite ramappa1994%}+++

|$\beta_v$
|infection rate of susceptible vectors by an infected plant
| +++{%cite Butter1978 ramappa1994 %}+++

|$r_1$, $r_2$
|replanting rate of latent and infected plants
| +++{% cite Nateshan1996 %}+++

|$b$
| latency rate
| +++{% cite Nateshan1996 %}+++

| $\gamma$, $\gamma_f$
| natural and fumigation vector death rate
| +++{% cite Holt1999 Cohen2007 %}+++

|$\mu$
| vector migration rate from alternative plants to crop
| +++{% cite Ramappa1998 %}+++

| $\theta$
| proportion of infected vector from migration
| +++{% cite ramappa1994 Ramappa1998 %}+++
|===

[#fig:fitnonresistance]

.Figure {counter:figure-number} Callibration Confidence bands for cumulative disease incidence of link:#eq:DeterministicSystem[model (1)]
for non-resistant tomato data. Squares denote Rashmi, and points PSCL-4 tomato species data. The blue and red line
represents the median incidence curve. Parameter values fixed in Table 2.
Data from Holt and Muniyappa. Digital edition figures feasible in https://plotly.com/AdrianSalcedo/347/[].

lightbox::example-standalone[ 800, {data-image-figure-1}, role="mb-4" ]

[#fig:fitresistance]

.Figure {counter:figure-number} Confidence bands of cumulative disease incidence to resistan tdata set.
($\color{darkblue}{\blacksquare}$,$\color{orange}{\bullet}$) LA1582, and
Tyking tomato species data.
The blue and red line represents the median incidence curve.
Parameter values fixed in link:tbl:parameter_value[Table 1].
Data from Holt and Muniyappa +++{% cite Holt1999 %}+++.
See https://plotly.com/~AdrianSalcedo/339/[] for a interactive visualization.

lightbox::example-standalone[ 800, {data-image-figure-2}, role="mb-4" ]

TODO: Reproduce Table 2.


[#subsec:deterministic_fixed_points]
=== Deterministic Fixed Points

According to  ODE link:#eq:DeterministicSystem[(1)], let
$N_v^{\infty}:= {\mu}/{( \gamma + \gamma_f)}$.
Let $\mathbf{R} ^ 5$ and consider the set
++++
    \begin{equation*}
        %\label{eqn:invariant_set}
	    \Gamma:=
		    \left \{
			(S_p, L_p, I_p, S_v, I_v)^{\top} \in \mathbf{R} ^ 5: \
			0\leq S_p + L_p + I_p \leq N_p, \quad
			0 \leq S_v + I_v \leq N_v^{\infty}
		\right \}.
    \end{equation*}
++++
Note that
[#eqn:plant_size]
++++
\begin{equation}\label{eqn:plant_size}
    \begin{aligned}
        \frac{d N_p}{dt} &=
			\frac{d}{dt}(S_p + L_p + I_p) = 0,
			\\
        \frac{d N_v}{dt} &=
            \mu - ( \gamma + \gamma_f) N_v.
    \end{aligned}
\end{equation}
++++
Thus the whole plant population $N_p(t)$ remains
constant for all $t\geq 0$. In addition,
\begin{equation}
    \label{eqn:vector_size}
    N_v(t)= N^{\infty}_v +
        (N_v(0) - N^{\infty}_v) \exp(-( \gamma + \gamma_f) t) .
\end{equation}
From this relation, we conclude that
$
    \lim_{t\to\infty}
    N_v(t) = N_v^{\infty},
$
and that population sizes $N_p(t)$, $N_v(t)$ satisfies a
conservative law. To summarize, we prove that set $\Gamma$
is positive invariant in the sense of the following
definition +++{% cite Meiss2007 --locator 106 %}+++.
++++
<div class="definition", text='Invariant set '>
    <p>
            Let $f:[0,T]\times \Gamma \subset \mathbb{R}^n\to \mathbb{R}^n$.
        We say that $\Gamma $ is an invariant set under $f$,
        if $f(t,\Gamma)\subset \Gamma$ for all $t\in [0, T]$.
    </p>
</div>
++++


[#thm:positive_invariance]
++++
    <div class="theorem", text='Positive-invariance'>
        <p>
            The set $\Gamma$ is positive invariant.
        </p>
    </div>
++++

++++
<div class="proof">
    <p>
        Let $(S_p,L_p,I_p,S_v,I_v)^\top \in \Gamma$ and apply the
        right-hand side of dynamic <a href="#eq:DeterministicSystem">(1)</a>.
        We have
        \begin{align*}
                \frac{dS_p}{dt}
                    &=
                    -\beta_p S_p
                \frac{I_v}{N_v} + r_1 L_p + r_2 I_p ,
            \\
                \frac{dL_p}{dt}
                    &=
                        \beta_p S_p\frac{I_v}{N_v} - (b + r_1) L_p ,
            \\
                \frac{dI_p}{dt}
                    &=
                        b L_p - r_2 I_p,
            \\
                \frac{dS_v}{dt}
                    &=
                        -\beta_v S_v\frac{I_p}{N_p} -
                        ( \gamma + \gamma_f) S_v+(1-\theta) \mu ,
            \\
                \frac{dI_v}{dt}
                    &=
                        \beta_v S_v \frac{I_p}{N_p} - ( \gamma + \gamma_f) I_v
                        + \theta \mu.
         \end{align*}
         Now, verifying $\Gamma$ conditions, we get
        $dS_p / dt + dL_p / dt + dI_p / dt \leq dN_p / dt$.
        By law conservation
        <a href="#eqn:plant_size">
            (2)
        </a>,
        $S_p+L_p+I_p\leq N_p$.
        Similarly,
        $
            dS_v / dt +  dI_v / dt \leq \mu  -(\gamma + \gamma_f) (S_v + I_v) \leq
            \mu - ( \gamma + \gamma_f) N_v
        $.
        Further, from relation \eqref{eqn:vector_size}, we obtain
        $
            S_v+I_v\leq N^{\infty}_v+(N_v(0)-N^{\infty}_v)\exp{(-
     	( \gamma + \gamma_f) t)}
        $.
        Since this is for all $t$, we have $S_v+I_v\leq N^{\infty}_v$, hence
        $f(S_p,L_p,I_p,S_v,I_v) \in \Gamma$. Therefore, $\Gamma$ is
        invariant under
        <a href="#eq:DeterministicSystem">
            System (1)
        </a>
        <span class="right">
            $\square$.
        </span>
    </p>
</div>
++++

System link:#eq:DeterministicSystem[(1)] has the following fixed points:
++++
Free disase Equilibrium
$$
    FDE:= \left(
        N_p,0,0,N^{\infty}_v,0
        \right)^{\top}.
$$
++++
and the Endemic Equilibrium
++++
$$
    EE:=(S_p^{**},
    L_p^{**},
    I_p^{**},
    S_v^{**},
    I_v^{**}).
$$
++++


Here we compute this deterministic fixed points of ODE
link:#eq:DeterministicSystem[(1)]---more details +++{% cite Salcedo-varela2021 %}+++ ---and show that its uniqueness.
To determine this fixed points, we solve,

[#eqn:fixed_points]
\begin{equation}
     \label{eqn:fixed_points}
 	\begin{aligned}
 		-\beta_p S_p \frac{I_v}{N_v} + r_1L_p+r_2I_p &= 0\\
 		\beta_p S_p \frac{I_v}{N_v} - (b + r_1) L_p &= 0\\
 		b L_p - r_2 I_p &= 0\\
 		-\beta_v S_v \frac{I_p}{N_p} -( \gamma + \gamma_f) S_v +(1-\theta) \mu &= 0\\
 		\beta_v S_v \frac{I_p}{N_p} -( \gamma + \gamma_f) I_v + \theta \mu &= 0.
 	\end{aligned}
 \end{equation}
Note that link:#eqn:fixed_points[Eq. (4)] has at least
two solutions---the free disease $(FDE)$
and the endemic $(EE)$ fixed point. To characterize
the free disease solution
+++$ FDE:= (S_{p} ^ *, L_{p}^*, I_{p}^*, S_{v}^*, I_{v}^*)$+++,
we assume that
+++${L^*_p = I_p^* = I_v^* = 0}$+++.
Consequently, from relation link:eqn:plant_size[(2)],
the first component of link:#eqn:fixed_points[Eq. (4)]
implies +++${S_p ^ * = N_p}$+++. Moreover,
from \eqref{eqn:vector_size} we see that
+++$S_v ^ * + I_v ^ * \to N^{\infty}_v $+++ as
$t \to \infty$, then
+++$ S_v^* \to N^{\infty}_v$+++.
Therefore, FDE results
+++
$$
     FDE:= \left(
         N_p,0,0,N^{\infty}_v,0
         \right)^{\top}.
$$
+++
For the endemic fixed point
+++$
     EE:=(S_p^{**},
     L_p^{**},
     I_p^{**},
     S_v^{**},
     I_v^{**})
$+++,
we assume that components +++$L_p^{**}$+++, +++$I_p^{**}$+++, +++$I_v^{**}$+++
are positive and solve the right-hand side of
\eqref{sys::DeterministicSystem} in terms of +++$I_v^{**}$+++.
From link:#eqn:fixed_points[Eq. (4)] we obtain
++++
\begin{equation*}
	\begin{aligned}
		S^{**}_p &=
 		    \frac{
                (r_1 L^{**}_p + r_2 I ^ {**} _ p) N_v
            }{
                I^{**}_v \beta_{p}
            }
         \\
 		L^{**}_p &=
		    \frac{
 		        \beta_{p} S_p^{**} I_v^{**}
 		    }{
 		        N_v \left( b+r_1 \right)
 		    },
 		\\
 		I ^ {**} _ p &=
            \frac{b L^{**}_p}{r_2},
 		\\
 		S^{**}_v &=
 			\frac{
 				\left(
 					1-\theta
 				\right)
 				\mu\, N_{p}
 			}{
 				( \gamma + \gamma_f)\, N_{p} + I^{**}_p
 				\beta_{v}
 			}.
 	\end{aligned}
 \end{equation*}
++++
Expressing the above relations in terms of +++$L_p^{**}, I^{**}_p$+++ results
++++
\begin{equation}
     \label{eqn:endemic_point_components}
 	\begin{aligned}
 	    S^{**}_p &=
 		    \frac{
                (r_1 L^{**}_p + r_2 I^{**}_p) N_v
            }{
                I^{**}_v \beta_{p}
            },
 	\\
 	L^{**}_p &=
 		\frac{
 			r_1L_p^{**} + r_2 I^{**}_p
 		}{
 		b + r_1
 		},
 	\\
 	I^{**}_p &=
 		\frac{
 			b (r_1 L_p^{**} + r_2 I_p^{**})
 		}{
 			 \left(
 			 	 b + r_1
 			 \right)
 			  r_2
 		},
 	\\
 	S^{**}_v &=
 		\frac{
 			 \left(
 			 	1 - \theta
 			 \right)
 			 \mu(b + r_1)
 			 r_2N_p
 		}{
 			( \gamma + \gamma_f) N_p(b + r_1)
 			r_2 +
            b
            (
                r_1 L_p ^ {**} + r_2
                I_p ^ {**}
            )
            \beta_v
 		}.
 	\end{aligned}
 \end{equation}
++++
//
Substituting the above relations into the $I_v$ component of
link:#eq:DeterministicSystem[ODE (1)] yields
++++
\begin{align*}
 		&[
 		    b ( \gamma + \gamma_f) \beta_p I ^ {**}_v +
 		    b ( \gamma + \gamma_f) N_v r_2 +
 		    b \beta_p \beta_v I^{**}_v +
 		    ( \gamma + \gamma_f) \beta_p r_2 I^{**}_v
 		    \\
 		    &+
 		    ( \gamma + \gamma_f) N_v r_1 r_2
 		] I^{**}_v
  		=
  		N_v
  		(
  		    b ( \gamma + \gamma_f) \theta \beta_p I^{**}_v +
  		    b ( \gamma + \gamma_f) \theta N_v r_2
  		 \\
  		 &+
  		    ( \gamma + \gamma_f) \theta \beta_p r_2 I^{**}_v +
  		    ( \gamma + \gamma_f) \theta N_v r_1 r_2 +
  		    b \beta_p \beta_v I^{**}_v
  		).
 	\end{align*}
++++

Let
//
++++
 \begin{align*}
 	a_1 &:=
 		(\gamma + \gamma_f) \beta_p (b + r_2) +
 		b \beta_p \beta_v
 		,\\
 	a_2 &:=
 	    (\gamma + \gamma_f) N_v [r_2 (b + r_1) - \beta_p \theta (b + r_2)]
 	    - N_v b \beta_p \beta_v
 	    ,
 	\\
 	a_3 &:=
 	    (\gamma + \gamma_f) {N_v}^2 r_2 \theta (b + r_1).
 \end{align*}
++++
//
So, after some algebraic manipulations, we establish
the following quadratic equation
++++
 \begin{equation}\label{eqn::QuadraticInfectedFP}
     	    a_1 I_v^{**2} + a_2 I^{**}_v - a_3 = 0.
 \end{equation}
++++
According to the discriminant $\Delta = a_2  ^ 2 -  4a_1 a_3$,
we get
++++
 \begin{equation*}
     \begin{aligned}
         \Delta
             &=
                 \{
                 (\gamma + \gamma_f) N_v [r_2 (b + r_1)
                 - \beta_p \theta (b + r_2)]
 	            - N_v b \beta_p \beta_v
                 \} ^ 2
             \\
             & +
                 4[
                 ( \gamma + \gamma_f) \beta_p (b + r_2) +
 	            b \beta_p \beta_v
                 )
                 (
                 (\gamma + \gamma_f) {N_v}^2 r_2 \theta (b + r_1)
                 ].
     \end{aligned}
 \end{equation*}
++++
Note that $\Delta$ is positive, this implies two real solutions
++++
 \begin{equation}
     \label{eqn:I_v_positiity}
 	I^{**}_{v} =
 		\frac{
 			-a_2 +
 			\sqrt{a_2^2 - 4a_1 a_3}}%
 		{2a_1}.
 \end{equation}
++++
From relations \eqref{eqn:endemic_point_components} and \eqref{eqn:I_v_positiity}
we obtain endemic fixed point $EE$.
And using van den Driessche's +++{% cite VandenDriessche2017a %}+++ definition of basic reproductive
number to compute basic reproductivenumber
$\mathcal{R}^d_0$ as the spectral radius of the next-generation matrix.
For the system link:#eq:DeterministicSystem[(1)] next-generation matrix results
++++
\begin{equation*}\label{Mtx::NextGenerationMatrix}
     K:=
         \begin{bmatrix}
         0 & 0 &\frac{\beta_p S^*_p}{N^{\infty}_v ( \gamma + \gamma_f)}
         \\
         0 & 0 & 0
         \\
         \frac{\beta_v S^*_v b}{N_p (b+r_1) r_2} &
         \frac{\beta_v S^*_v}{N_p r_2} & 0
         \\
         \end{bmatrix}.
 \end{equation*}
++++
Matrix $K$  has $(i, j)$ entry equal to the expected number of secondary
infections in the compartment $i$ produced by an infected individual introduced
in the compartment $j$. Calculating the basic reproductive number for the system
link:#eq:DeterministicSystem[(1)] we have
++++
\begin{equation*}%\label{eqn::DeterministicBRN}
    \mathcal{R}^d_0:=\frac{\beta_p \beta_v b}{(b + r_1 ) ( \gamma + \gamma_f) r_2}.
\end{equation*}
++++

The following result give a criteria for the stability of fixed points using basic
reproductive number $\mathcal{R}^d_0$ +++{% cite VandenDriessche2017a %}+++.

++++
<div class="theorem" text="Thm.1, p.292 VandenDriessche(2017)">

    If $\mathcal{R}^d_0 < 1$, then the fixed point FDE of system
    (1) is locally asymptotically stable.
</div>
++++
Besides,  when $\mathcal{R}^d_0>1$ we have the instability
of free disease fixed point, but we obtain the stability
of the endemic fixed point, and we establish the following result.

[#Thm::StabilityEndemicPointBasicReproNumberDeter]
++++
<div class="theorem">
    <p>
        If $\mathcal{R}^d_0>1$, then the fixed point EE of
        <a href="#eq:DeterministicSystem">
            System (1)
        </a>
        is locally asymptotically stable.
    </p>
</div>
++++



[#sec:stochastic_extension]
== Stochastic Extension

In this section, we derive our stochastic differential equation from
system link:#eq:DeterministicSystem[(1)]. Following ideas from
+++{% cite Schurz2015 %}+++,
we quantify uncertainty in plant-replanting $r_1$, $r_2$, and vector-die
by fumigation $\gamma_f$
using a standard Brownian process and the suitable smooth functions.
Let $x:=(S_p, I_p, L_p, S_v,I_v)^{\top}$, then we consider the functions
$F_i: \mathbb{R} \to \mathbb{R}$, $i \in\{ r_1, r_2, \gamma_f \}$
defined by

\begin{equation}
        F_{r_1}(x)
            :=
            \sigma_L
            \frac{S_p}{N_p},
        \qquad
        F_{r_2}(x)
            :=
            \sigma_I
            \frac{S_p}{N_p},
        \qquad
        F_{\gamma_f}(x)
            :=
            \sigma_v.
\end{equation}

Where $F_i$ are locally Lipschitz-continuous on $\Gamma$. Let
$B(t) = (B_p(t), B_v(t))^{\top}$ be a 2-dimensional standard Brownian process
defined on a filtered complete probability space
$(\Omega,\mathcal{F},\{\mathcal{F}_t\}_{t\geq 0},\P)$.
%, and $dB(t)=B(t+dt)-B(t)$ denotes the increment of a standard Brownian process.
Thus, we perturb the deterministic model link:#eq:DeterministicSystem[(1)]
replacing the rates $r_1$, $r_2$, and $\gamma_f$ by

[#eqn:NoisePerturbation]
\begin{equation}
	\label{eqn:NoisePerturbation}
	\begin{aligned}
		r_1 dt \rightsquigarrow r_1 dt
		+ \sigma_L \frac{S_p}{N_p} dB_p(t),
    		\\
		r_2 dt \rightsquigarrow r_2 dt
		+ \sigma_I \frac{S_p}{N_p} dB_p(t),
		\\
		\gamma_f dt \rightsquigarrow \gamma_f dt + \sigma_v dB_v(t).
	\end{aligned}
\end{equation}

Note that the right-hand side of link:eqn:NoisePerturbation[(4)] denotes a
stochastic perturbation of $r_1$, $r_2$, $\gamma_f$.

So, we deduce a stochastic extension from deterministic system
link:#eq:DeterministicSystem[(1)] given the following Itô SDE:

\begin{equation}
	\label{sys::StochasticSystem}
	\begin{aligned}
		d S_p &=
			\left(
				-\beta_p S_p \frac{I_v}{N_v} + r_1 L_p + r_2 I_p
			\right)dt
			+ \frac{S_p(\sigma_L L_p
			+
			\sigma_I I_p)}{N_p}dB_p(t),
		\\
		dL_p &=
			\left(
				\beta_p S_p \frac{I_v}{N_v} - (b + r_1) L_p
			\right) dt
			- \sigma_L \frac{S_pL_p}{N_p} dB_p(t),
		\\
		d I_p &=
			\left(
				b L_p - r_2 I_p
			\right) dt
			- \sigma_I \frac{S_pI_p}{N_p} dB_p(t),
		\\
		dS_v &=
			\left(
				-\beta_v S_v \frac{I_p}{N_p} - (\gamma + \gamma_f) S_v  +
				 (1-\theta) \mu	\right)dt - \sigma_v S_v dB_v(t),
		\\
		d I_v &=
			\left(
				\beta_v S_v \frac{I_p}{N_p} - (\gamma + \gamma_f) I_v + \theta \mu
			\right) dt
			- \sigma_v I_v dB_v(t),
			 \\
			& S_p(0) = S_{p}^{0}, \quad
            L_p(0) = L_{p}^{0}, \quad
            I_p(0) = I_{p}^{0}, \quad
            \\
            & S_v(0) = S_{v}^{0},
              I_v(0) = I_{v}^{0}.
	\end{aligned}
\end{equation}

[#sec:solution_existence]
== Existence and uniqueness of positive Solution
++++
<p>
        Here, we prove the existence of a unique positive solution.
    Since we study the asymptotic behavior of a biological model,
    we have to assure the existence of unique-globally-positive
    invariant solution of SDE
    \eqref{sys::StochasticSystem}. The following result prove that
    this set is positive invariant-- see supplementary material.
</p>

<div class="theorem" id="thm::existence-unique">

        For any initial values
        $
            (S_p(0), L_p(0), I_p(0), S_v(0), I_v(0))^{\top}
            \in \Gamma
        $,
        exists a unique a.s. invariant global positive solution to SDE
        \eqref{sys::StochasticSystem} in $\Gamma$, that is, the solution
        $x(t) = (S_p(t), L_p(t), I_p(t), S_v(t), I_v(t)) ^\top$, satisfies
        \begin{equation*}
            \mathbb{P}
                \Big\{
                    x(t)
                    \in
                    \Gamma, \
                    \forall t \geq 0
                \Big\} = 1.
        \end{equation*}
    </div>
++++

++++
    <div class="proof">
        <p>
                To prove existence of global solution, note that the right-hand side of
            \eqref{sys::StochasticSystem} are second-order polynomials, are locally
            Lipschitz continuous. By Theorem 3.4 {% cite Mao2008 --locator 56 %},
            there exists a unique local solution
            $(S_p(t),L_p(t),I_p(t),S_v(t),I_v(t))^\top$
            defined on $[0,\tau_e)$, where $\tau_e$ is the explosion time.
            We will show $\tau_e = \infty$ a.s.
        </p>
        <p>
                Let $k_0>0$ such that
            $$
                (S_p(0),L_p(0),I_p(0),S_v(0),I_v(0))^\top \in
             	\left(
                    \frac{1}{k_0},k_0\right)
                    \times
                    \dots
                    \times
                    \left(\frac{1}{k_0},k_0
                \right)=
            	\left(\frac{1}{k_0},k_0\right)^5.
            $$
        </p>

        <p>
                For any $k>0$ with $k>k_0$, define
            \begin{equation*}
         	    \tau_k :=
                    \inf
                        \left \{
                            t\in [0,\tau_e)
             	                :(S_p(t),L_p(t),I_p(t),S_v(t),I_v(t))^\top
             	                    \not \in
                                        \left(
                                            \frac{1}{k},k
                                        \right)^5
                        \right\}.
         	\end{equation*}
         	Note that $\tau_k$ is an increasing sequence, because
         	$\left(1/k,k\right)$ is an increasing sequence. Moreover,
         	$\tau_k \leq \tau_e$. Then $\tau_k$ has a limit, denote by
         	$\tau_{\infty}$. We will show that $\tau_{\infty}=\infty$;
         	this implies $\tau_e = \infty$ and we conclude hat system
         	\eqref{sys::StochasticSystem} has a unique solution and will
         	remain in $\Gamma$ with probability one.
        </p>

        <p>
 	            We proceed by a contradiction. Suppose $\tau_{\infty}<\infty$.
            Thus, there exists $T>0$ such that

            $$
         	    \mathbb{P}
                    \Big\{
                        \tau_{\infty} < T
                    \Big\}
                    >\epsilon, \quad \forall
         	        \epsilon \in (0,1).
         	$$
            Thus, there exists $k_1>k_0$ such that
         	$\mathbb{P} \Big\{ \tau_k<T \Big\} >\epsilon$ for all $k \geq k_1$.
        <\p>
        <p>
            We consider the	following Lyapunov function $V:\mathbb{R}^5 \to \mathbb{R}$ by
         	\begin{equation*}
 	            \begin{aligned}
                    & V (S_p, L_p, I_p, S_v, I_v) :=
                        \left(S_p - N_p - N_p \log{\frac{S_p}{N_p}}\right) +
                        \left(L_p - N_p - N_p \log{\frac{L_p}{N_p}}\right)
                    \\
                    &+
                        \left(I_p - N_p - N_p \log{\frac{I_p}{N_p}}\right) +
                        \left(S_v - N^{\infty}_v - N^{\infty}_v
                        \log{\frac{S_v}{N^{\infty}_v}}\right)
                    \\
                    &+
                        \left(I_v - N^{\infty}_v - N^{\infty}_v
                        \log{\frac{I_v}{N^{\infty}_v}}\right).
 	            \end{aligned}
     	    \end{equation*}
 	        Applying the diffusion operator $\mathcal{L}$ see {% cite Mao2008 --locator 12 %}, to
            $$
                f(x) = x - N - N\
                \log{
                    \left( \frac{x}{N} \right)
                },
            $$
            we get
            \begin{align*}
                &\mathcal{L}[V(S_p,L_p,I_p,S_v,I_v)] =
                    \left(
                            1 - \frac{N_p}{S_p}
                        \right) \left(
                           -\frac{\beta_p}{N_v} S_p I_v + r_1 L_p + r_2 I_p
                        \right)
                        \\
                        &+
                            \left(
                                1 - \frac{N_p}{L_p}
                            \right) \left(
                               \frac{\beta_p}{N_v} S_p I_v -(b + r_1) L_p
                            \right) + \left(
                                1 - \frac{N_p}{I_p}
                            \right) \left(
                               b L_p - r_2 I_p
                            \right)
                        \\
                        &+
                            \left(
                                1 - \frac{N^{\infty}_v}{S_v}
                            \right) \left(
                           -\frac{\beta_v}{N_p} S_v I_p - (\gamma + \gamma_f) S_v +
                            (1- \theta) \mu
                        \right)
                        \\
                        &+ \left(
                        1 - \frac{N^{\infty}_v}{I_v}
                        \right) \left(
                           -\frac{\beta_v}{N_p} S_v I_p -
                            (\gamma + \gamma_f) I_v + \theta \mu
                            \right)
                        \\
                        &+
                            \frac{1}{2}\frac{S_p ^2}{N_p ^ 2}
                            \frac{N_p}{S_p ^ 2} (\sigma_L L_p + \sigma_I I_p) ^ 2
                            + \frac{1}{2} \sigma_L ^2
                            \frac{S_p ^2}{N_p ^2} L_p^2 \frac{N_p}{L_p ^2}
                            + \frac{1}{2} \sigma_I ^2
                            \frac{S_p ^2}{N_p ^2} I_p^2 \frac{N_p}{I_p ^2}
                       \\
                        &+
                            \frac{1}{2} \sigma_v ^2 S_v ^2 \frac{N^{\infty}_v}{S_v ^2}
                            + \frac{1}{2} \sigma_v ^2 I_v ^2 \frac{N^{\infty}_v}{I_v ^2}.
            \end{align*}
 	    </p>
        <p>
            Bounding the above equality by positive terms, we have
            \begin{equation}\label{eqn::boudn1positvesol}
                \begin{aligned}
                    &\mathcal{L}[V(S_p,L_p,I_p,S_v,I_v)] \leq
                        \frac{\beta_p}{N_v} S_p I_v + r_1 L_p + r_2 I_p
                        + \frac{\beta_p}{N_v} S_p I_v
                        + (b + r_1) L_p
                        \\
                        &+
                            b L_p + r_2 N_p + (1 - \theta) \mu
                            + \frac{\beta_v}{N_p} S_v I_p
                            + (\gamma + \gamma_f) N^{\infty}_v
                            + \frac{\beta_v}{N_p} S_v I_p + \theta \mu
                       \\
                        &+ (\gamma + \gamma_f) N^{\infty}_v
                        + \frac{1}{2} \frac{1}{N_p} (\sigma_L L_p + \sigma_I I_p)^2
                            + \frac{1}{2}\sigma_L ^2
                            \frac{S_p ^2}{N_p} + \frac{1}{2}\sigma_I ^2
                            \frac{S_p ^2}{N_p}
                        \\
                        &+ \frac{1}{2}\sigma_v ^2 N^{\infty}_v
                            + \frac{1}{2} \sigma_v ^2 N^{\infty}_v.
                \end{aligned}
            \end{equation}
        </p>
 	    <p>>
            Using size population, we bound \eqref{eqn::boudn1positvesol} by
     	    \begin{equation}\label{eqn::boudn2positvesol}
     	        \begin{aligned}
     	            &\mathcal{L}[V(S_p,L_p,I_p,S_v,I_v)] \leq
             	        \beta_p N_p + r_1 N_p + r_2 N_p + \beta_p N_p
             	        + (b + r_1) N_p
         	        \\
             	        &+
         	            b N_p + r_2 N_p + (\gamma + \gamma_f) N^{\infty}_v
         	            + \beta_v N^{\infty}_v
         	            + (\gamma + \gamma_f) N^{\infty}_v +\beta_v N^{\infty}_v +
         	            (\gamma + \gamma_f) N^{\infty}_v
         	       \\
             	        &+ (\gamma + \gamma_f) N^{\infty}_v
         	            + (\gamma + \gamma_f) N^{\infty}_v
         	        	+ \frac{1}{2} (\sigma_L + \sigma_I)^2 N_p
         	            + \frac{1}{2}\sigma_L ^2
         	            N_p + \frac{1}{2} \sigma_I ^2 N_p
                    \\
             	        &+
         	        	\frac{1}{2}\sigma_v ^2 N^{\infty}_v
         	            + \frac{1}{2} \sigma_v ^2 N^{\infty}_v.
         	    \end{aligned}
     	    \end{equation}
         	Factorizing by $N_p$ and $N^{\infty}_v$ relation \eqref{eqn::boudn2positvesol},
     	    we get
            \begin{equation*}\label{eqn::boudn3positvesol}
             	\begin{aligned}
                    \mathcal{L}[V(S_p,L_p,I_p,S_v,I_v)] &
                    \\
                      \leq &
                        \left(
                            2 \beta_p + 2 r_1 + 2 r_2 + 2 b +
                            \frac{1}{2} (\sigma_L + \sigma_I)^2
                            + \frac{1}{2}\sigma_L ^2
                            + \frac{1}{2} \sigma_I ^2
                        \right) N_p
                    \\
                    + &
                        [
                            2 \beta_v  + 4 (\gamma + \gamma_f) + \sigma_v ^2
                        ]
                        N^{\infty}_v.
                \end{aligned}
            \end{equation*}
 	    </p>
 	    <p>
                Define
            \begin{equation*}\label{eqn::boudn4positvesol}
                \begin{aligned}
                   C_1  := &
                        \left(
                            2 \beta_p + 2 r_1 + 2 r_2 + 2 b +
                            \frac{1}{2} (\sigma_L + \sigma_I)^2
                            + \frac{1}{2}\sigma_L ^2
                            + \frac{1}{2} \sigma_I ^2
                        \right) N_p
                        \\
                        + &
                            [
                            2 \beta_v  + 4 (\gamma + \gamma_f) + \sigma_v ^2
                            ] N^{\infty}_v.
                \end{aligned}
            \end{equation*}
 	        Then by Ito's formula, we obtain
            \begin{equation}\label{eqn::boudn5positvesol}
                \begin{aligned}
                    &d[V(S_p,L_p,I_p,S_v,I_v)] \leq
                        C_1 dt + \left(
                            1- \frac{N_p}{S_p}
                            \right)\left[\frac{S_p}{N_p}(
                            \sigma_L L_p + \sigma_I I_p)\right]dB_p(t)
                   \\
                    &+
                        \left(1 - \frac{N_p}{L_p}\right)
                        \left(
                        - \sigma_L \frac{S_p}{N_p} L_p
                        \right)dB_p(t)
                       + \left(1 - \frac{N_p}{I_p}\right)
                       \left(
                       - \sigma_I \frac{S_p}{N_p} I_p
                       \right)dB_p(t)
                   \\
                    &+
                       \left(1 - \frac{N^{\infty}_v}{S_v}\right)
                       \left(- \sigma_v S_v\right)dB_v(t) +
                       \left(1 - \frac{N^{\infty}_v}{I_v}\right)
                       \left(- \sigma_v I_v\right)dB_v(t).
                \end{aligned}
            \end{equation}
        </p>
        <p>
                Bounding \eqref{eqn::boudn5positvesol} by positive terms
            \begin{equation}\label{eqn::boudn6positvesol}
                \begin{aligned}
                    &d[V(S_p,L_p,I_p,S_v,I_v)] \leq
                        C_1 dt + \left[\frac{S_p}{N_p}
                        (\sigma_L L_p + \sigma_I I_p)\right]dB_p(t)
                   \\
                    &+
                        (\sigma_L + \sigma_I) dB_p(t)
                        + 2 \sigma_v N^{\infty}_v dB_p(t).
                \end{aligned}
            \end{equation}
         	Integrating both sides of \eqref{eqn::boudn6positvesol} on
         	$(0,\tau_k \wedge T)$, taking expectation, we have

         	\begin{equation*}\label{eqn::boudn7positvesol}
     	        \begin{aligned}
                    &\E{[V(S_p,L_p,I_p,S_v,I_v)]} \leq
                        V(S_p(0),L_p(0),I_p(0),S_v(0),I_v(0))
                   \\
                    &+
                        \E{\int_0^{\tau_k \wedge T} C_1 dt}
                        + \E{\int_0^{\tau_k \wedge T}
                        \left[\frac{S_p}{N_p}
                        (\sigma_L L_p + \sigma_I I_p)\right]dB_p(t)}
                    \\
                    &+
                        \E{\int_0^{\tau_k \wedge T}
                        (\sigma_L + \sigma_I) dB_p(t)} +
                        2 \E{ \int_0^{\tau_k \wedge T}
                        \sigma_v N^{\infty}_v dB_p(t)}.
                \end{aligned}
            \end{equation*}
         	Since $G \in L^2(0, T)$, then $\E{\int_0^T G dB(s)}=0$. Using the above argument, we obtain

% 	\begin{equation*}\label{eqn::boudn8positvesol}
%     	\begin{aligned}
%     	    &\E{[V(S_p,L_p,I_p,S_v,I_v)]} \leq
%     	        V(S_p(0),L_p(0),I_p(0),S_v(0),I_v(0))
%     	       + C_1 T.
%     	\end{aligned}
% 	\end{equation*}
% 	%
% 	For $k \geq 1$ such that $k \geq k_0$, let
% 	$\Omega_k = \{ \tau_k \leq T\}$. Then,	$\probX{\Omega_k} > \epsilon$.
% 	If $t \in \Omega_k$, thus at least one of the following	will hold true:
% 	%
%     \begin{align*}
%         S_p(t) \not \in &\left( \frac{1}{k}, k\right), \qquad L_p(t) \not \in
%         \left( \frac{1}{k}, k\right), \qquad  I_p(t) \not \in
%         \left( \frac{1}{k}, k\right), \\
%          &S_v(t) \not \in \left( \frac{1}{k}, k\right), \qquad  I_v(t) \not \in
%          \left( \frac{1}{k}, k\right).
%     \end{align*}
%     %
%     Note that, $f(x) = x - N_{\bullet} - N_{\bullet}\log{x/N_{\bullet}}$ is
%     increasing on $(N_{\bullet},\infty)$ and decreasing on $(0,N_{\bullet})$
%     it follows
% 	%
% 	\begin{align*}
% 	    &V(S_p(\tau_k \wedge T),L_p(\tau_k \wedge T),I_p(\tau_k \wedge T),
% 	        S_v(\tau_k \wedge T),I_v(\tau_k \wedge T)) \geq
% 	        \\
% 	           &
% 	            \left(k - N_p - N_p \log{\frac{k}{N_p}}\right)^3
% 	            \wedge \left(\frac{1}{k} - N_p - N_p
% 	            \log{\frac{1}{N_p k}}\right)^3 \wedge
% 	        \\
% 	           &
% 	            \left(k - N^{\infty}_v - N^{\infty}_v
% 	            \log{\frac{k}{N^{\infty}_v}}\right)^2
% 	            \wedge \left(\frac{1}{k} - N^{\infty}_v - N^{\infty}_v
% 	            \log{\frac{1}{N^{\infty}_v k}}\right)^2.
%  	\end{align*}
%  	%
%  	Now we have
%  	%
%  	\begin{align*}
%  	      &V(S_p(0),L_p(0),I_p(0),S_v(0),I_v(0)) + C_1 T
%  	      \geq \E{[V(S_p,L_p,I_p,S_v,I_v)]}
%  	    \\
%  	      &\geq
%  	        \epsilon \left(k - N_p - N_p \log{\frac{k}{N_p}}\right)^3 \wedge \left(
%  	        \frac{1}{k} - N_p - N_p \log{\frac{1}{N_p k}}\right)^3 \wedge
% 	        \\
% 	           &
% 	            \left(k - N^{\infty}_v - N^{\infty}_v
% 	            \log{\frac{k}{N^{\infty}_v}}\right)^2
% 	            \wedge \left(\frac{1}{k} - N^{\infty}_v - N^{\infty}_v
% 	            \log{\frac{1}{N^{\infty}_v k}}\right)^2.
%  	\end{align*}
%  	%
%  	Finally, letting $ k \to \infty$ we obtain
%     %
%  	\begin{equation*}
%  	    \infty > V(S_p(0),L_p(0),I_p(0),S_v(0),I_v(0)) + C_1 T \geq \infty,
%  	\end{equation*}
%  	%
%  	which is a contradiction. Thus, we conclude that $\tau_\infty = \infty$.
% \end{proof}

    </div>>
++++





[#sec:extinction]
== Extinction

[#sec:persistence]
== Persistence

[#sec:numerics]
== Numerical Experiments


== References

++++
{% bibliography --file References.bib %}
++++

